config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get ':year/:mon', to: 'home#index', as: :home_dated, format: false, constraints: {year: /\d{4}/, mon: /\d{1,2}/}

  get 'feed', to: 'feed#show', as: :feed
  get 'calendar', to: 'calendar#show', as: :calendar

  get '/signin', to: 'sessions#new', as: :sign_in
  get '/signout', to: 'sessions#destroy', as: :sign_out

  # no names, as these routes should never be referenced from app code
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @date = if params[:year].present? && params[:mon].present?
      Date.parse("#{params[:year]}-#{params[:mon]}-01")
    else
      Date.today
    end
    @prev_date = @date.beginning_of_month - 1
    @next_date = @date.end_of_month + 1
    period = [@date.beginning_of_month.beginning_of_week, @date.end_of_month.end_of_week]
    trips = Trip.in_period(*period).order(category: :asc)
    defaults = (period.first..period.last).each_with_object({}) { |date, m| m[date] = [] }
    @trips = trips.each_with_object(defaults) do |trip, m|
      (trip.starts_on..trip.ends_on).each { |date| m[date] ||= []; m[date] << trip }
    end
  end
end

app/views/home/index.html.erb
<div class="pull-right">
  <ul class="calendar-pager pager">
    <li>
      <%= link_to fa_icon('chevron-left'),
                  home_dated_path(year: @prev_date.year, mon: sprintf("%02d", @prev_date.mon)) %>
    </li>
    <li><%= link_to 'Today', root_path %></li>
    <li>
      <%= link_to fa_icon('chevron-right'),
                  home_dated_path(year: @next_date.year, mon: sprintf("%02d", @next_date.mon)) %>
    </li>
  </ul>
</div>

<div class="calendar-title"><%= @date.strftime "%B %Y" %></div>

<div class="clearfix"></div>

<%= bootstrap_calendar @date do |date| %>
  <%= content_tag :span, class: "pull-right", "data-cal-date" => "some", "data-cal-view" => "day" do %>
    <%= date.day %>
  <% end %>
  <% if @trips[date].any? %>
    <ul class="list-unstyled">
      <% @trips[date].each do |trip| %>
        <li><%= trip_button trip %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<div class="text-center">
  <div class="btn-group calendar-tools">
    <%= link_to feed_url(format: :atom), class: 'btn btn-default' do %>
      <%= fa_icon 'rss' %> Add to feed reader
    <% end %>
    <div class="btn-group dropup">
      <%= button_tag class: 'btn btn-default dropdown-toggle', data: {toggle: 'dropdown'} do %>
        <%= fa_icon 'calendar' %> Subscribe to calendar <span class="caret"></span>
      <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to 'Microsoft Outlook', calendar_url(format: :ics, protocol: 'webcal') %></li>
        <li><%= link_to 'Apple iCal', calendar_url(format: :ics, protocol: 'webcal') %></li>
        <li>
          <%= link_to 'Google Calendar',
                      "http://www.google.com/calendar/render?cid=#{uri_escape_url calendar_url(format: :ics)}",
                      target: 'gcal' %>
        </li>
      </ul>
    </div>
  </div>
</div>

<footer>
  <p>All content courtesy of <%= link_to 'Outdoor Adventure Club, LLC', 'http://outdooradventureclub.com/' %>. Questions about trips or the club itself? <%= mail_to 'info@outdooradventureclub.com' %>. About this site? <%= mail_to 'bcm@maz.org' %>.</p>
</footer>