config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get ':year/:mon', to: 'home#index', as: :home_dated, format: false, constraints: {year: /\d{4}/, mon: /\d{1,2}/}

  get 'feed', to: 'feed#show', as: :feed
  get 'calendar', to: 'calendar#show', as: :calendar

  get '/signin', to: 'sessions#new', as: :sign_in
  get '/signout', to: 'sessions#destroy', as: :sign_out

  # no names, as these routes should never be referenced from app code
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Outdoor Adventure Club Trip Calendar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= tag(:meta, property: 'fb:app_id', content: Rails.application.secrets.facebook_app_id) %>
    <% if signed_in? %>
      <%= tag(:meta, name: 'oac:identity', content: current_user.email) %>
    <% end %>
  </head>
  <body role="document">
    <div id="fb-root"></div>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-controls">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Outdoor Adventure Club Trip Calendar', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="navbar-controls">
          <div class="navbar-right">
            <% if signed_in? %>
              <p class="navbar-text"><%= current_user.email %></p>
              <ul class="nav navbar-nav">
                <li><%= link_to 'Sign out', sign_out_path, id: 'signout' %></li>
              </ul>
            <% else %>
              <% unless current_page?(sign_in_path) %>
                <ul class="nav navbar-nav">
                  <li><%= link_to 'Sign up or sign in', sign_in_path %></li>
                </ul>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <div id="main" class="container" role="main">
      <%= alert_boxes %>
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>